-   id: swatch
    name: swatch
    description: Automatically upgrade syntax for newer versions.
    entry: swatch
    language: python
    types: [python]
    # for backward compatibility
    files: ''
    minimum_pre_commit_version: 0.15.0
