name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.9
        architecture: x64

    - name: Install dependencies
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: install -d

    - name: Run tests
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run pytest

    - name: Run linter
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run pylint src --reports=y

    - name: Run type checks
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run mypy src
