name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.9
        architecture: x64
    - name: Install dependecies
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: make setup

    - run: make check
